version: '3.7'
services:
  app:
    build: .
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports: ['${MONGO_PORT}:${MONGO_PORT}']
